import type { Support } from '@/types'

/**
 * 시드 데이터: 정부 지원금 30개
 *
 * Supabase 연결 없이 개발/테스트할 때 사용하는 로컬 데이터
 * 실제 서비스에서는 Supabase DB에서 조회
 */
export const SEED_SUPPORTS: Support[] = [
  // 금융 (5개)
  {
    id: 'seed-finance-001',
    title: '소상공인 정책자금 융자',
    organization: '소상공인시장진흥공단',
    category: '금융',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    detailUrl: 'https://www.semas.or.kr/web/SUP/supportFund.kmdc',
    targetRegions: ['서울', '경기', '인천'],
    targetBusinessTypes: ['음식점업', '소매업', '기타서비스업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 10,
    targetRevenueMin: null,
    targetRevenueMax: 5000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 7천만원, 이자 2.0% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-finance-002',
    title: '청년창업자 특례보증',
    organization: '중소기업진흥공단',
    category: '금융',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    detailUrl: 'https://www.kibo.or.kr/src/main.do',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 50,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: 36,
    targetFounderAgeMin: null,
    targetFounderAgeMax: 39,
    amount: '최대 1억원 보증, 보증료 0.5% 감면',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-finance-003',
    title: '중소기업 성장지원 융자',
    organization: '중소벤처기업부',
    category: '금융',
    startDate: '2025-01-01',
    endDate: null,
    detailUrl: 'https://www.kosmes.or.kr/sbc/SH/SBI/SHSBI004M0.do',
    targetRegions: null,
    targetBusinessTypes: ['제조업', '정보통신업'],
    targetEmployeeMin: 5,
    targetEmployeeMax: 300,
    targetRevenueMin: null,
    targetRevenueMax: 100000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 30억원, 이자 1.5% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-finance-004',
    title: '소상공인 희망대출',
    organization: '신용보증재단중앙회',
    category: '금융',
    startDate: '2025-03-01',
    endDate: '2025-11-30',
    detailUrl: 'https://www.semas.or.kr/web/SUP/supportFund.kmdc',
    targetRegions: null,
    targetBusinessTypes: ['음식점업', '소매업', '숙박업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 5,
    targetRevenueMin: null,
    targetRevenueMax: 3000000000,
    targetBusinessAgeMin: 1,
    targetBusinessAgeMax: 120,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 2천만원, 이자 3.0%',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-finance-005',
    title: '기술보증기금 스타트업 특별보증',
    organization: '기술보증기금',
    category: '금융',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    detailUrl: 'https://www.kibo.or.kr/src/main.do',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 30,
    targetRevenueMin: null,
    targetRevenueMax: 30000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: 60,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 5억원, 보증료 0.3% 감면',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 기술 (3개)
  {
    id: 'seed-tech-001',
    title: '중소기업 R&D 지원사업',
    organization: '중소벤처기업부',
    category: '기술',
    startDate: '2025-01-01',
    endDate: '2026-06-30',
    detailUrl: 'https://www.smtech.go.kr',
    targetRegions: null,
    targetBusinessTypes: ['제조업', '정보통신업'],
    targetEmployeeMin: 10,
    targetEmployeeMax: null,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: 36,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 3억원, 개발비 80% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-tech-002',
    title: 'AI·빅데이터 기술개발 지원',
    organization: '한국산업기술진흥원',
    category: '기술',
    startDate: '2025-02-01',
    endDate: '2026-08-31',
    detailUrl: 'https://www.iitp.kr',
    targetRegions: ['서울', '경기', '대전'],
    targetBusinessTypes: ['정보통신업'],
    targetEmployeeMin: 5,
    targetEmployeeMax: 100,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 5억원, 연구개발비 75% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-tech-003',
    title: '스마트공장 구축 지원',
    organization: '중소벤처기업부',
    category: '기술',
    startDate: '2025-01-01',
    endDate: null,
    detailUrl: 'https://www.smart-factory.kr',
    targetRegions: null,
    targetBusinessTypes: ['제조업'],
    targetEmployeeMin: 20,
    targetEmployeeMax: null,
    targetRevenueMin: 10000000000,
    targetRevenueMax: null,
    targetBusinessAgeMin: 60,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 1억원, 구축비 50% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 인력 (4개)
  {
    id: 'seed-hr-001',
    title: '청년 일자리 도약 장려금',
    organization: '고용노동부',
    category: '인력',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.ei.go.kr',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 30,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '청년 1인당 월 80만원, 최대 12개월',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-hr-002',
    title: '중소기업 청년 인턴십',
    organization: '중소벤처기업부',
    category: '인력',
    startDate: '2025-01-01',
    endDate: '2026-10-31',
    detailUrl: 'https://www.work.go.kr',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: 5,
    targetEmployeeMax: 300,
    targetRevenueMin: null,
    targetRevenueMax: 50000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '인턴 1인당 월 100만원, 3개월',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-hr-003',
    title: '고용창출장려금',
    organization: '고용노동부',
    category: '인력',
    startDate: '2025-01-01',
    endDate: null,
    detailUrl: 'https://www.ei.go.kr/ei/eih/eg/pb/pbPersonBnef/retrievePb0203Info.do',
    targetRegions: ['부산', '대구', '광주', '울산'],
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 50,
    targetRevenueMin: null,
    targetRevenueMax: 20000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '신규 고용 1인당 월 60만원, 최대 12개월',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-hr-004',
    title: '일학습병행 지원금',
    organization: '한국산업인력공단',
    category: '인력',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.bizhrd.net',
    targetRegions: null,
    targetBusinessTypes: ['제조업'],
    targetEmployeeMin: 10,
    targetEmployeeMax: null,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '훈련생 1인당 월 40만원, 훈련비 100% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 창업 (5개)
  {
    id: 'seed-startup-001',
    title: '예비창업패키지',
    organization: '중소벤처기업부',
    category: '창업',
    startDate: '2025-01-01',
    endDate: '2026-03-31',
    detailUrl: 'https://www.k-startup.go.kr',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 5,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: 12,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 1억원, 창업비용 100% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-startup-002',
    title: '청년창업사관학교',
    organization: '중소벤처기업부',
    category: '창업',
    startDate: '2025-02-01',
    endDate: '2026-04-30',
    detailUrl: 'https://start.kosmes.or.kr',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 3,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: 24,
    targetFounderAgeMin: null,
    targetFounderAgeMax: 39,
    amount: '최대 1억원, 사업화 자금 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-startup-003',
    title: '서울시 청년창업지원',
    organization: '서울시',
    category: '창업',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.seoul.go.kr/main/index.jsp',
    targetRegions: ['서울'],
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 10,
    targetRevenueMin: null,
    targetRevenueMax: 3000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: 36,
    targetFounderAgeMin: null,
    targetFounderAgeMax: 39,
    amount: '최대 5천만원, 임차료·인건비 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-startup-004',
    title: '소상공인 재창업 지원',
    organization: '소상공인시장진흥공단',
    category: '창업',
    startDate: '2025-01-01',
    endDate: null,
    detailUrl: 'https://www.semas.or.kr',
    targetRegions: null,
    targetBusinessTypes: ['음식점업', '소매업', '기타서비스업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 5,
    targetRevenueMin: null,
    targetRevenueMax: 2000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 3천만원, 창업비용 70% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-startup-005',
    title: '경기도 청년창업 1000+ 프로젝트',
    organization: '경기도',
    category: '창업',
    startDate: '2025-03-01',
    endDate: '2026-09-30',
    detailUrl: 'https://www.gyeonggi.go.kr',
    targetRegions: ['경기'],
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 5,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: 24,
    targetFounderAgeMin: null,
    targetFounderAgeMax: 39,
    amount: '최대 2천만원, 사무공간·멘토링 제공',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 경영 (8개)
  {
    id: 'seed-mgmt-001',
    title: '소상공인 온라인 판로개척 지원',
    organization: '소상공인시장진흥공단',
    category: '경영',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.semas.or.kr/web/SUP/supportOnlineBiz.kmdc',
    targetRegions: null,
    targetBusinessTypes: ['소매업', '음식점업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 10,
    targetRevenueMin: null,
    targetRevenueMax: 3000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 500만원, 온라인 판로개척 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-mgmt-002',
    title: '중소기업 해외마케팅 지원',
    organization: '중소벤처기업부',
    category: '경영',
    startDate: '2025-01-01',
    endDate: null,
    detailUrl: 'https://www.kotra.or.kr',
    targetRegions: null,
    targetBusinessTypes: ['제조업', '정보통신업'],
    targetEmployeeMin: 10,
    targetEmployeeMax: null,
    targetRevenueMin: 5000000000,
    targetRevenueMax: null,
    targetBusinessAgeMin: 36,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 2억원, 수출 마케팅비 50% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-mgmt-003',
    title: '소상공인 경영개선 컨설팅',
    organization: '소상공인시장진흥공단',
    category: '경영',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.semas.or.kr',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 10,
    targetRevenueMin: null,
    targetRevenueMax: 5000000000,
    targetBusinessAgeMin: 12,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '무료 컨설팅 제공, 최대 20시간',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-mgmt-004',
    title: '중소기업 디지털 전환 지원',
    organization: '중소기업진흥공단',
    category: '경영',
    startDate: '2025-02-01',
    endDate: '2026-11-30',
    detailUrl: 'https://www.kosmes.or.kr',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: 5,
    targetEmployeeMax: 100,
    targetRevenueMin: null,
    targetRevenueMax: 50000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 5천만원, 디지털화 비용 70% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-mgmt-005',
    title: '소상공인 배달앱 수수료 지원',
    organization: '서울시',
    category: '경영',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.mss.go.kr',
    targetRegions: ['서울'],
    targetBusinessTypes: ['음식점업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 5,
    targetRevenueMin: null,
    targetRevenueMax: 2000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '배달앱 수수료 50% 환급, 월 최대 100만원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-mgmt-006',
    title: '중소기업 특허출원 지원',
    organization: '특허청',
    category: '경영',
    startDate: '2025-01-01',
    endDate: null,
    detailUrl: 'https://www.kipa.org',
    targetRegions: null,
    targetBusinessTypes: ['제조업', '정보통신업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 50,
    targetRevenueMin: null,
    targetRevenueMax: 30000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '특허출원료 100% 지원, 최대 10건',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-mgmt-007',
    title: '소상공인 에너지 효율화 지원',
    organization: '한국에너지공단',
    category: '경영',
    startDate: '2025-03-01',
    endDate: '2026-10-31',
    detailUrl: 'https://www.semas.or.kr',
    targetRegions: null,
    targetBusinessTypes: ['음식점업', '제조업', '숙박업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 20,
    targetRevenueMin: null,
    targetRevenueMax: 10000000000,
    targetBusinessAgeMin: 36,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 1천만원, 설비교체 비용 80% 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-mgmt-008',
    title: '중소기업 수출바우처',
    organization: '중소벤처기업부',
    category: '경영',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.exportvoucher.com',
    targetRegions: null,
    targetBusinessTypes: ['제조업'],
    targetEmployeeMin: 5,
    targetEmployeeMax: null,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 2천만원, 수출활동 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 기타 (5개)
  {
    id: 'seed-other-001',
    title: '재난피해 소상공인 특별지원',
    organization: '소상공인시장진흥공단',
    category: '기타',
    startDate: '2025-01-01',
    endDate: '2026-06-30',
    detailUrl: 'https://www.mss.go.kr',
    targetRegions: null,
    targetBusinessTypes: ['음식점업', '소매업', '숙박업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 10,
    targetRevenueMin: null,
    targetRevenueMax: 3000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '최대 2천만원, 피해복구 지원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-other-002',
    title: '착한임대인 세액공제',
    organization: '국세청',
    category: '기타',
    startDate: '2025-01-01',
    endDate: null,
    detailUrl: 'https://www.nts.go.kr',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: null,
    targetRevenueMin: null,
    targetRevenueMax: null,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '임대료 인하액의 70% 세액공제',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-other-003',
    title: '소상공인 전기요금 특별지원',
    organization: '중소벤처기업부',
    category: '기타',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.mss.go.kr/site/smba/ex/bbs/View.do',
    targetRegions: null,
    targetBusinessTypes: ['음식점업', '소매업', '제조업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 10,
    targetRevenueMin: null,
    targetRevenueMax: 5000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '전기요금 20% 감면, 월 최대 50만원',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-other-004',
    title: '중소기업 사회보험료 지원',
    organization: '고용노동부',
    category: '기타',
    startDate: '2025-01-01',
    endDate: null,
    detailUrl: 'https://www.work.go.kr',
    targetRegions: null,
    targetBusinessTypes: null,
    targetEmployeeMin: null,
    targetEmployeeMax: 30,
    targetRevenueMin: null,
    targetRevenueMax: 10000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '사회보험료 50% 지원, 최대 12개월',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-other-005',
    title: '부산시 소상공인 재난지원금',
    organization: '부산광역시',
    category: '기타',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    detailUrl: 'https://www.busan.go.kr',
    targetRegions: ['부산'],
    targetBusinessTypes: ['음식점업', '소매업', '기타서비스업'],
    targetEmployeeMin: null,
    targetEmployeeMax: 5,
    targetRevenueMin: null,
    targetRevenueMax: 2000000000,
    targetBusinessAgeMin: null,
    targetBusinessAgeMax: null,
    targetFounderAgeMin: null,
    targetFounderAgeMax: null,
    amount: '업체당 200만원 일시 지급',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
