import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('Error: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables must be set.');
  console.error('Copy .env.local.example to .env.local and fill in your values.');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY);

const supports = [
  // 금융 (5개)
  {
    title: '소상공인 정책자금 융자',
    organization: '소상공인시장진흥공단',
    category: '금융',
    start_date: '2025-01-01',
    end_date: '2025-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=10001',
    target_regions: ['서울', '경기', '인천'],
    target_business_types: ['음식점업', '소매업', '기타서비스업'],
    target_employee_min: null,
    target_employee_max: 10,
    target_revenue_min: null,
    target_revenue_max: 5000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '최대 7천만원, 이자 2.0% 지원',
  },
  {
    title: '청년창업자 특례보증',
    organization: '중소기업진흥공단',
    category: '금융',
    start_date: '2025-01-01',
    end_date: '2025-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=10002',
    target_regions: null,
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 50,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: 36,
    amount: '최대 1억원 보증, 보증료 0.5% 감면',
  },
  {
    title: '중소기업 성장지원 융자',
    organization: '중소벤처기업부',
    category: '금융',
    start_date: '2025-01-01',
    end_date: null,
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=10003',
    target_regions: null,
    target_business_types: ['제조업', '정보통신업'],
    target_employee_min: 5,
    target_employee_max: 300,
    target_revenue_min: null,
    target_revenue_max: 100000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '최대 30억원, 이자 1.5% 지원',
  },
  {
    title: '소상공인 희망대출',
    organization: '신용보증재단중앙회',
    category: '금융',
    start_date: '2025-03-01',
    end_date: '2025-11-30',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=10004',
    target_regions: null,
    target_business_types: ['음식점업', '소매업', '숙박업'],
    target_employee_min: null,
    target_employee_max: 5,
    target_revenue_min: null,
    target_revenue_max: 3000000000,
    target_business_age_min: 1,
    target_business_age_max: 120,
    amount: '최대 2천만원, 이자 3.0%',
  },
  {
    title: '기술보증기금 스타트업 특별보증',
    organization: '기술보증기금',
    category: '금융',
    start_date: '2025-01-01',
    end_date: '2025-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=10005',
    target_regions: null,
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 30,
    target_revenue_min: null,
    target_revenue_max: 30000000000,
    target_business_age_min: null,
    target_business_age_max: 60,
    amount: '최대 5억원, 보증료 0.3% 감면',
  },
  // 기술 (3개)
  {
    title: '중소기업 R&D 지원사업',
    organization: '중소벤처기업부',
    category: '기술',
    start_date: '2025-01-01',
    end_date: '2026-06-30',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=20001',
    target_regions: null,
    target_business_types: ['제조업', '정보통신업'],
    target_employee_min: 10,
    target_employee_max: null,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: 36,
    target_business_age_max: null,
    amount: '최대 3억원, 개발비 80% 지원',
  },
  {
    title: 'AI·빅데이터 기술개발 지원',
    organization: '한국산업기술진흥원',
    category: '기술',
    start_date: '2025-02-01',
    end_date: '2026-08-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=20002',
    target_regions: ['서울', '경기', '대전'],
    target_business_types: ['정보통신업'],
    target_employee_min: 5,
    target_employee_max: 100,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '최대 5억원, 연구개발비 75% 지원',
  },
  {
    title: '스마트공장 구축 지원',
    organization: '중소벤처기업부',
    category: '기술',
    start_date: '2025-01-01',
    end_date: null,
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=20003',
    target_regions: null,
    target_business_types: ['제조업'],
    target_employee_min: 20,
    target_employee_max: null,
    target_revenue_min: 10000000000,
    target_revenue_max: null,
    target_business_age_min: 60,
    target_business_age_max: null,
    amount: '최대 1억원, 구축비 50% 지원',
  },
  // 인력 (4개)
  {
    title: '청년 일자리 도약 장려금',
    organization: '고용노동부',
    category: '인력',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=30001',
    target_regions: null,
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 30,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '청년 1인당 월 80만원, 최대 12개월',
  },
  {
    title: '중소기업 청년 인턴십',
    organization: '중소벤처기업부',
    category: '인력',
    start_date: '2025-01-01',
    end_date: '2026-10-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=30002',
    target_regions: null,
    target_business_types: null,
    target_employee_min: 5,
    target_employee_max: 300,
    target_revenue_min: null,
    target_revenue_max: 50000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '인턴 1인당 월 100만원, 3개월',
  },
  {
    title: '고용창출장려금',
    organization: '고용노동부',
    category: '인력',
    start_date: '2025-01-01',
    end_date: null,
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=30003',
    target_regions: ['부산', '대구', '광주', '울산'],
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 50,
    target_revenue_min: null,
    target_revenue_max: 20000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '신규 고용 1인당 월 60만원, 최대 12개월',
  },
  {
    title: '일학습병행 지원금',
    organization: '한국산업인력공단',
    category: '인력',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=30004',
    target_regions: null,
    target_business_types: ['제조업'],
    target_employee_min: 10,
    target_employee_max: null,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '훈련생 1인당 월 40만원, 훈련비 100% 지원',
  },
  // 창업 (5개)
  {
    title: '예비창업패키지',
    organization: '중소벤처기업부',
    category: '창업',
    start_date: '2025-01-01',
    end_date: '2026-03-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=40001',
    target_regions: null,
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 5,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: 12,
    amount: '최대 1억원, 창업비용 100% 지원',
  },
  {
    title: '청년창업사관학교',
    organization: '중소벤처기업부',
    category: '창업',
    start_date: '2025-02-01',
    end_date: '2026-04-30',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=40002',
    target_regions: null,
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 3,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: 24,
    amount: '최대 1억원, 사업화 자금 지원',
  },
  {
    title: '서울시 청년창업지원',
    organization: '서울시',
    category: '창업',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=40003',
    target_regions: ['서울'],
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 10,
    target_revenue_min: null,
    target_revenue_max: 3000000000,
    target_business_age_min: null,
    target_business_age_max: 36,
    amount: '최대 5천만원, 임차료·인건비 지원',
  },
  {
    title: '소상공인 재창업 지원',
    organization: '소상공인시장진흥공단',
    category: '창업',
    start_date: '2025-01-01',
    end_date: null,
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=40004',
    target_regions: null,
    target_business_types: ['음식점업', '소매업', '기타서비스업'],
    target_employee_min: null,
    target_employee_max: 5,
    target_revenue_min: null,
    target_revenue_max: 2000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '최대 3천만원, 창업비용 70% 지원',
  },
  {
    title: '경기도 청년창업 1000+ 프로젝트',
    organization: '경기도',
    category: '창업',
    start_date: '2025-03-01',
    end_date: '2026-09-30',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=40005',
    target_regions: ['경기'],
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 5,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: 24,
    amount: '최대 2천만원, 사무공간·멘토링 제공',
  },
  // 경영 (8개)
  {
    title: '소상공인 온라인 판로개척 지원',
    organization: '소상공인시장진흥공단',
    category: '경영',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=50001',
    target_regions: null,
    target_business_types: ['소매업', '음식점업'],
    target_employee_min: null,
    target_employee_max: 10,
    target_revenue_min: null,
    target_revenue_max: 3000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '최대 500만원, 온라인 판로개척 지원',
  },
  {
    title: '중소기업 해외마케팅 지원',
    organization: '중소벤처기업부',
    category: '경영',
    start_date: '2025-01-01',
    end_date: null,
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=50002',
    target_regions: null,
    target_business_types: ['제조업', '정보통신업'],
    target_employee_min: 10,
    target_employee_max: null,
    target_revenue_min: 5000000000,
    target_revenue_max: null,
    target_business_age_min: 36,
    target_business_age_max: null,
    amount: '최대 2억원, 수출 마케팅비 50% 지원',
  },
  {
    title: '소상공인 경영개선 컨설팅',
    organization: '소상공인시장진흥공단',
    category: '경영',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=50003',
    target_regions: null,
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 10,
    target_revenue_min: null,
    target_revenue_max: 5000000000,
    target_business_age_min: 12,
    target_business_age_max: null,
    amount: '무료 컨설팅 제공, 최대 20시간',
  },
  {
    title: '중소기업 디지털 전환 지원',
    organization: '중소기업진흥공단',
    category: '경영',
    start_date: '2025-02-01',
    end_date: '2026-11-30',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=50004',
    target_regions: null,
    target_business_types: null,
    target_employee_min: 5,
    target_employee_max: 100,
    target_revenue_min: null,
    target_revenue_max: 50000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '최대 5천만원, 디지털화 비용 70% 지원',
  },
  {
    title: '소상공인 배달앱 수수료 지원',
    organization: '서울시',
    category: '경영',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=50005',
    target_regions: ['서울'],
    target_business_types: ['음식점업'],
    target_employee_min: null,
    target_employee_max: 5,
    target_revenue_min: null,
    target_revenue_max: 2000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '배달앱 수수료 50% 환급, 월 최대 100만원',
  },
  {
    title: '중소기업 특허출원 지원',
    organization: '특허청',
    category: '경영',
    start_date: '2025-01-01',
    end_date: null,
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=50006',
    target_regions: null,
    target_business_types: ['제조업', '정보통신업'],
    target_employee_min: null,
    target_employee_max: 50,
    target_revenue_min: null,
    target_revenue_max: 30000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '특허출원료 100% 지원, 최대 10건',
  },
  {
    title: '소상공인 에너지 효율화 지원',
    organization: '한국에너지공단',
    category: '경영',
    start_date: '2025-03-01',
    end_date: '2026-10-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=50007',
    target_regions: null,
    target_business_types: ['음식점업', '제조업', '숙박업'],
    target_employee_min: null,
    target_employee_max: 20,
    target_revenue_min: null,
    target_revenue_max: 10000000000,
    target_business_age_min: 36,
    target_business_age_max: null,
    amount: '최대 1천만원, 설비교체 비용 80% 지원',
  },
  {
    title: '중소기업 수출바우처',
    organization: '중소벤처기업부',
    category: '경영',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=50008',
    target_regions: null,
    target_business_types: ['제조업'],
    target_employee_min: 5,
    target_employee_max: null,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '최대 2천만원, 수출활동 지원',
  },
  // 기타 (5개)
  {
    title: '재난피해 소상공인 특별지원',
    organization: '소상공인시장진흥공단',
    category: '기타',
    start_date: '2025-01-01',
    end_date: '2026-06-30',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=60001',
    target_regions: null,
    target_business_types: ['음식점업', '소매업', '숙박업'],
    target_employee_min: null,
    target_employee_max: 10,
    target_revenue_min: null,
    target_revenue_max: 3000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '최대 2천만원, 피해복구 지원',
  },
  {
    title: '착한임대인 세액공제',
    organization: '국세청',
    category: '기타',
    start_date: '2025-01-01',
    end_date: null,
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=60002',
    target_regions: null,
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: null,
    target_revenue_min: null,
    target_revenue_max: null,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '임대료 인하액의 70% 세액공제',
  },
  {
    title: '소상공인 전기요금 특별지원',
    organization: '중소벤처기업부',
    category: '기타',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=60003',
    target_regions: null,
    target_business_types: ['음식점업', '소매업', '제조업'],
    target_employee_min: null,
    target_employee_max: 10,
    target_revenue_min: null,
    target_revenue_max: 5000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '전기요금 20% 감면, 월 최대 50만원',
  },
  {
    title: '중소기업 사회보험료 지원',
    organization: '고용노동부',
    category: '기타',
    start_date: '2025-01-01',
    end_date: null,
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=60004',
    target_regions: null,
    target_business_types: null,
    target_employee_min: null,
    target_employee_max: 30,
    target_revenue_min: null,
    target_revenue_max: 10000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '사회보험료 50% 지원, 최대 12개월',
  },
  {
    title: '부산시 소상공인 재난지원금',
    organization: '부산광역시',
    category: '기타',
    start_date: '2025-01-01',
    end_date: '2026-12-31',
    detail_url: 'https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?seq=60005',
    target_regions: ['부산'],
    target_business_types: ['음식점업', '소매업', '기타서비스업'],
    target_employee_min: null,
    target_employee_max: 5,
    target_revenue_min: null,
    target_revenue_max: 2000000000,
    target_business_age_min: null,
    target_business_age_max: null,
    amount: '업체당 200만원 일시 지급',
  },
];

async function main() {
  console.log('Inserting 30 support programs...');

  const { data, error } = await supabase
    .from('supports')
    .insert(supports)
    .select('id, title');

  if (error) {
    console.error('Insert error:', error);
    process.exit(1);
  }

  console.log(`\nSuccessfully inserted ${data.length} support programs:`);
  data.forEach((s) => console.log(`  - ${s.title}`));
  console.log('\nDatabase setup complete!');
}

main();
